apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.deployment.api.name }}
  name: {{ .Values.deployment.api.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.api.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.deployment.api.name }}
    spec:
      containers:
        - image: {{ .Values.deployment.api.image }}:{{ .Values.deployment.api.version }}
          name: {{ .Values.deployment.api.name }}
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_USER
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: API_PORT
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_PASSWORD
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_DB_NAME
          resources: {}
status: {}
