apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.deployment.client.name }}
  name: {{ .Values.deployment.client.name }}-service
spec:
  ports:
  - name: {{ .Values.deployment.client.port }}-{{ .Values.deployment.client.port }}
    port: {{ .Values.deployment.client.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.client.port }}
  selector:
    app: {{ .Values.deployment.client.name }}
  type: LoadBalancer
status:
  loadBalancer: {}
